version: "3"
services:
  pgweb:
    image: "sosedoff/pgweb:latest"
    env_file:
      - .env.production
    ports:
      - 8088:8081
    command: ["sleep 3; /usr/bin/pgweb --bind=0.0.0.0 --listen=8081"]
